codestates-seb/seb44_main_017

server/src/main/java/com/main/project/ProjectApplication.java
server/src/main/java/com/main/project/admin/entity/Admin.java
server/src/main/java/com/main/project/comment/ProductComment.java
server/src/main/java/com/main/project/dto/MultiResponseDto.java
server/src/main/java/com/main/project/dto/PageInfo.java
server/src/main/java/com/main/project/dto/SingleResponseDto.java
server/src/main/java/com/main/project/exception/BusinessLogicException.java
server/src/main/java/com/main/project/exception/ExceptionCode.java
server/src/main/java/com/main/project/helper/audit/Auditable.java
server/src/main/java/com/main/project/helper/validator/NotSpace.java
server/src/main/java/com/main/project/helper/validator/NotSpaceValidator.java
server/src/main/java/com/main/project/member/dto/MemberDto.java
server/src/main/java/com/main/project/member/entity/Member.java
server/src/main/java/com/main/project/member/entity/RefreshToken.java
server/src/main/java/com/main/project/member/repository/MemberRepository.java
server/src/main/java/com/main/project/product/controller/ProductController.java
server/src/main/java/com/main/project/product/dto/ProductDto.java
server/src/main/java/com/main/project/product/entity/Product.java
server/src/main/java/com/main/project/product/mapper/ProductMapper.java
server/src/main/java/com/main/project/product/repository/ProductRepository.java
server/src/main/java/com/main/project/product/service/ProductService.java
server/src/main/java/com/main/project/response/ErrorResponse.java
server/src/main/java/com/main/project/response/ListResponseDto.java
server/src/main/java/com/main/project/response/SingleResponseDto.java

[feat] Product Entity, Service, Dto, mapper, repo added. Read Operation OK. ProductComment entity added

[feat] Product Entity, Service, Dto, mapper, repo added. Read Operation OK. ProductComment entity added

---

server/src/main/java/com/main/project/exception/ExceptionCode.java
server/src/main/java/com/main/project/notifyBoard/controller/NotifyController.java
server/src/main/java/com/main/project/notifyBoard/dto/NotifyDto.java
server/src/main/java/com/main/project/notifyBoard/entity/NotifyBoard.java
server/src/main/java/com/main/project/notifyBoard/mapper/NotifyMapper.java
server/src/main/java/com/main/project/notifyBoard/repository/NotifyRepository.java
server/src/main/java/com/main/project/notifyBoard/service/NotifyService.java

공지사항(등록,수정,삭제,조회) 구현

---

server/src/main/java/com/main/project/comment/ProductComment.java
server/src/main/java/com/main/project/product/controller/ProductController.java
server/src/main/java/com/main/project/product/mapper/ProductMapper.java
server/src/main/java/com/main/project/product/service/ProductService.java

[feature] Product CRUD

---

client/src/App.tsx
client/src/components/Header/Header.tsx
client/src/components/Modal_login/LoginModal.tsx
client/src/components/Modal_signup/SignupModal.tsx
client/src/components/Modal_signup/style.ts

- 회원가입 버튼 클릭 시 모달창 On
- 회원가입 모달창 내 X 버튼 클릭 시 모달창 Off
- CSS 수정

feat: 회원가입 모달창 On/Off

---

client/src/components/Modal_login/LoginModal.tsx
client/src/components/Modal_login/style.ts
client/src/components/Modal_signup/SignupModal.tsx
client/src/components/Modal_signup/style.ts

feat: 로그인 모달창 구현

---

client/src/components/Modal_signup/SignupModal.tsx
client/src/components/Modal_signup/style.ts

feat: 회원가입 API 구현

---

client/src/components/Collection_form/CollectionForm.tsx
client/src/components/Collection_form/style.ts
client/src/components/SelectBox/SelectBox.tsx
client/src/components/SelectBox/style.ts
client/src/constants/constants.tsx
client/src/pages/collectionPage/collectionPage.tsx
client/src/pages/collectionPage/style.ts

[기능 gif 링크](https://blog.kakaocdn.net/dn/GpbHI/btsnhTjA1DQ/sedPK44eYiU0qyObVFEBKk/img.gif)
셀렉트 박스 기능 수정
- props를 추가로 넘겨서 정렬용과 카테고리용을 구분함

[feat] 의류 수거 요청 페이지 작업

---

client/src/assets/icons/Post.svg
client/src/components/Item_notify/NotifyItem.styles.ts
client/src/pages/noticePage/noticePage.tsx

서버에서 데이터 받아오는 것까지 테스트해보고 완료했습니다!
추후에 공지사항 등록일 표기 방식 수정하겠습니다.

[feat] 공지사항 컴포넌트 API 연동 완료

---

client/src/components/CategoryButton/CategoryButton.tsx
client/src/pages/productListPage/productListPage.tsx
client/src/pages/productListPage/style.tsx

feat: 상품리스트 페이지 구현

---

client/src/components/Modal_login/LoginModal.tsx
client/src/utils/token.tsx

client/src/utils/token.tsx 파일에 주석으로 함수 설명 적어두었습니다.
- authorization, refresh을 가져오기
- 사용자, 관리자 넥네임 가져오기
- 사용자, 관리자 Id 가져오기
- 사용자, 관리자 구분 가져오기 
- 쿠키에 저장된 정보 삭제하기 (회원탈퇴, 로그아웃 시 사용)

feat: 로그인 시 name, id, roles 저장

---

client/src/components/Modal_signup/SignupModal.tsx
client/src/pages/myinfoPage/myinfoPage.tsx
client/src/pages/myinfoPage/style.tsx

- feat: 회원정보수정 페이지 내 회원 탈퇴 시 메인페이지 이동
- feat: 회원가입 성공 시 메인 이동 및 모달창 close

feat: 회원 정보 수정 페이지 완료

---

client/src/assets/icons/Logout.tsx
client/src/components/Comment/Comment.tsx
client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
client/src/components/Dropdown_hamburger/style.ts
client/src/components/Dropdown_profile/ProfileDropdown.tsx
client/src/components/SelectBox/style.ts
client/src/types/shared.ts
client/src/utils/token.tsx

[refactor] 로그인, 비로그인 / 사용자, 관리자 조건부 렌더링 작업

---

client/src/pages/productInfoPage/ProductInfo.tsx
client/src/pages/productInfoPage/productInfoPage.tsx
client/src/pages/productInfoPage/style.ts

[feat] 상품 상세 페이지 API 연동 일부 성공

---

client/src/App.tsx
client/src/components/Footer/Footer.tsx
client/src/components/Footer/style.ts
client/src/components/Item_notify/NotifyItem.tsx
client/src/components/Item_notify/style.ts
client/src/components/SelectBox/SelectBox.tsx
client/src/pages/noticeDetailPage/noticeDetailPage.tsx
client/src/pages/noticePage/noticePage.tsx
client/src/pages/noticePage/style.tsx
client/src/pages/productListPage/style.tsx

feat: 공지사항 목록 페이지 구현

---

client/src/assets/icons/PointIcon.tsx
client/src/components/Dropdown_profile/ProfileDropdown.tsx
client/src/components/Item_product/ProductItem.tsx
client/src/components/Mypage_header/MypageHeader.tsx
client/src/constants/constants.tsx
client/src/pages/myproductsPage/myproductsPage.tsx
client/src/pages/shoppingCartPage/shoppingCartPage.tsx
client/src/pages/shoppingCartPage/style.ts
client/src/recoil/atom.ts
client/src/types/shared.ts

[시연 링크](https://blog.kakaocdn.net/dn/bIR0wo/btsogd3nutw/ZmZMRKUj5Kewk7PuLnEY80/img.gif)
- 장바구니에 데이터는 임의로 넣어서 작성하였습니다.
- 추후에 장바구니 담기 버튼을 따로 만들어서 연동시킨 후 테스트할 예정입니다~

[feat] 장바구니 페이지 작업

---

client/src/components/Comment/Comment.tsx
client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
client/src/pages/qnaDetailPage/qnaDetailPage.tsx
client/src/types/shared.ts

- Comment 컴포넌트를 QnA 상세페이지와 Product 상세페이지 두 곳에서 사용될 수 있도록 리팩토링 했습니다!

[refactor] Comment 컴포넌트 QnA와 Product에서 재사용되도록 리팩토링

---

client/src/pages/productInfoPage/ProductInfo.tsx
client/src/pages/productInfoPage/productInfoPage.tsx
client/src/pages/productInfoPage/style.ts

상품 삭제 기능 구현과 상품 상세 페이지 반응형 css를 적용했습니다.

[feat] 상품 상세페이지 게시물 삭제 기능 구현 및 반응형 대응

---

client/src/components/Pagination/CustomPagination.tsx

[design] 페이지네이션 컴포넌트 버튼 색상 변경

---

client/src/components/Register/Register.tsx
client/src/pages/noticeRegisterPage/noticeRegisterPage.tsx
client/src/pages/qnaRegisterPage/qnaRegisterPage.tsx

[feat] 공지, Q&A 등록 컴포넌트 구현 완료

---

client/src/components/Collection_form/style.ts
client/src/components/Comment/Comment.tsx
client/src/components/Comment/style.ts
client/src/components/Dropdown_profile/style.ts
client/src/components/Mypage_header/style.ts
client/src/components/Qna_list/qnaListComponent.tsx
client/src/components/Qna_list/style.ts
client/src/components/SelectBox/style.ts
client/src/pages/collectionPage/collectionPage.tsx
client/src/pages/collectionPage/style.ts
client/src/pages/myproductsPage/myproductsPage.tsx
client/src/pages/myproductsPage/style.ts
client/src/pages/qnaListPage/qnaListPage.tsx

[design] QnA 목록, 마이페이지, 셀렉트 박스, 의류 수거 신청 페이지 등 UI 수정 작업

---

client/src/components/Comment/style.ts
client/src/pages/productInfoPage/ProductInfo.tsx
client/src/pages/productInfoPage/productInfoPage.tsx
client/src/pages/productInfoPage/style.ts
client/src/pages/productListPage/productListPage.tsx

[design] 상품 상세 페이지 및 코멘트 UI 수정 작업

---

client/src/components/CategoryButton/style.tsx
client/src/components/Modal_login/LoginModal.tsx
client/src/components/Modal_login/style.tsx
client/src/components/Modal_signup/SignupModal.tsx
client/src/components/Modal_signup/style.tsx
client/src/pages/productListPage/productListPage.tsx
client/src/pages/productListPage/style.tsx

- design: 로그인 디자인 수정
- design: 회원가입 디자인 수정
- feat: 휴대폰 번호 하이픈 자동 생성 및 닉네임 중복 검사 미진행 시 알럿 추가
- refactor: input 상태 여러개 관리하기 코드 수정
- feat: 추천 상품리스트, 일반 상품리스트 API 분리 및 브라우저 사이즈별 상품 갯수 변경
- design: 상품리스트 디자인 수정

feat: 로그인, 회원가입, 상품리스트 수정

---

client/src/App.tsx
client/src/components/Modify/Modify.tsx
client/src/components/Modify/style.ts
client/src/pages/noticeModifyPage/noticeModifyPage.tsx
client/src/pages/qnaModifyPage/qnaModifyPage.tsx

수정 컴포넌트 1차 완성

---

client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
client/src/components/Dropdown_profile/ProfileDropdown.tsx
client/src/components/Dropdown_profile/style.ts
client/src/components/Mypage_header/style.ts
client/src/components/Qna_list/style.ts
client/src/pages/myproductsPage/style.ts
client/src/pages/shoppingCartPage/shoppingCartPage.tsx
client/src/pages/shoppingCartPage/style.ts

- 드롭다운 위치, 사이드바 메뉴, 마이페이지 UI 수정

[fix] 드롭다운 위치, 사이드바 메뉴, 마이페이지 UI 수정

---

client/package-lock.json
client/package.json
client/src/components/Comment/Comment.tsx
client/src/components/Postcode/Postcode.tsx
client/src/pages/qnaDetailPage/qnaDetailPage.tsx
client/src/pages/shoppingCartPage/shoppingCartPage.tsx
client/src/pages/shoppingCartPage/style.ts
client/src/types/shared.ts

- 주소 입력 api 사용을 위해 설치한 라이브러리가 있으므로 npm install 해주세요!

[feat] 장바구니 결제 주소 입력 및 request 기능 구현

---

client/src/components/Comment/Comment.tsx
client/src/components/Mypage_header/style.ts
client/src/components/Postcode/Postcode.tsx
client/src/components/SubTItleBar/styled.ts
client/src/pages/myproductsPage/style.ts
client/src/pages/qnaDetailPage/qnaDetailPage.tsx
client/src/pages/qnaListPage/qnaListPage.tsx
client/src/utils/customConfirm.tsx
client/src/utils/customPrompt.tsx

[refactor] 커스텀 알림창 제작 & 반영

---

client/src/components/Modify/Modify.tsx
client/src/components/Modify/style.ts
client/src/components/Register/Register.tsx
client/src/components/Register/style.ts

[feat] 등록 & 수정 컴포넌트 내용 입력 창 줄바꿈 적용

---

client/src/components/BoardDetail/BoardDetail.tsx

질문 작성자와 이름이 일치할 때만 스피드 다이얼이 보이도록 수정했습니다.

[refactor] Q&A 상세 페이지 로그인 유저 이름과 질문 작성자가 일치해야 수정, 삭제 가능하게 변경

---

client/src/constants/constants.tsx

[chore] BASE_URL 주소 변경

---

client/src/components/BoardDetail/BoardDetail.tsx
client/src/components/Register/Register.tsx
client/src/components/SpeedDialCustom/SpeedDialCustom.tsx

사용자 이름 확인 과정에서 비동기 동작 관련 오류가 있어서 코드 수정했습니다.
[style] 불필요한 console.log 몇 개 제거했습니다.

[fix]  Q&A 상세 페이지 작성자 확인 기능이 작동하지 않는 현상 수정

---

client/src/components/Item_notify/NotifyItem.tsx
client/src/components/Item_notify/style.ts

[design] 공지사항 컴포넌트 포스트잇 svg 아이콘 제거 및 CSS 수정

Non fungible code

---

client/src/components/Postcode/Postcode.tsx
client/src/components/Qna_list/style.ts
client/src/hooks/useDebounce.ts
client/src/pages/productInfoPage/productInfoPage.tsx
client/src/pages/shoppingCartPage/shoppingCartPage.tsx

- 장바구니에 상품을 담으면 장바구니로 이동할지 목록으로 이동할지 confirm 메시지 출력
- 구매하기 후 상품 목록으로 이동

[fix] 장바구니 및 구매하기 후 navigate 추가

---

client/src/components/Item_product/ProductItem.tsx
client/src/pages/productInfoPage/ProductInfo.tsx
client/src/pages/productInfoPage/productInfoPage.tsx
client/src/pages/productInfoPage/style.ts
client/src/pages/productListPage/productListPage.tsx
client/src/pages/shoppingCartPage/shoppingCartPage.tsx

1. 상품 상태 승인대기 상태 추가
2. 승인 대기중인 물품 상세페이지 못가게 예외처리
3. 장바구니에 이미 있는 물건에 대해 장바구니 추가했을 경우 예외처리
4. 단일 결제가 주소, 결제할 포인트을 입력하지 않는 관계로 단일, 장바구니 결제 통합

# fix : update
